services:
  mysql:
    image: mysql:8.0
    container_name: foodmanager-mysql
    environment:
      MYSQL_DATABASE: foodmanager
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: foodmanager
      MYSQL_PASSWORD: foodmanager
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data: